[book]
authors = ["Carlos12001"]
language = "en"
multilingual = true
src = "src"
title = "Thoughts and Reflections"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/Carlos12001/thoughts-and-reflections"
